spring:
  profiles:
    active: dev
  # 数据库配置
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  resources:
    chain:
      strategy:
        content:
          enabled: true
      cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      additional-exclude: static/**,public/**,templates/**,mapper/*
  application:
    name: springOpenApi
logging:
  file:
    max-size: 10MB
    max-history: 20
    name: ./logs/springOpenApi.log
  level:
    root: warn
    com.example: info
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8302
  servlet:
    context-path: /springOpenApi
  max-http-header-size: 102400

---
# 测试环境
spring:
  profiles: dev
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
    druid:
      test-on-borrow: true
      test-while-idle: true
  # jpa 打印sql
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 10000
    password: 12345678
    database: 1
    jedis:
      pool:
        max-idle: 200
        max-wait: 10000

#swagger 配置
swagger:
  enable: true

#rabbitmq 配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#阿里云oss 配置
aliyun:
  oss:
    endpoint: cs
    accessKeyId: cs
    accessKeySecret: cs
    bucketName: cs