spring:
  profiles:
    active: dev
  # 数据库配置
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  resources:
    chain:
      strategy:
        content:
          enabled: true
      cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      additional-exclude: static/**,public/**,templates/**,mapper/*
  application:
    name: springWeb
logging:
  file:
    max-size: 10MB
    max-history: 20
    name: ./logs/springWeb.log
  level:
    root: warn
    com.example: info
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8301
  servlet:
    context-path: /springWeb
  max-http-header-size: 102400

---
# 测试环境
spring:
  profiles: dev
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
    druid:
      test-on-borrow: true
      test-while-idle: true
  # jpa 打印sql
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 10000
    password: 12345678
    database: 1
    jedis:
      pool:
        max-idle: 200
        max-wait: 10000
  mail:
    host: smtp.163.com
    username: 13333956278@163.com
    password: wq19961020
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#swagger 设置
swagger:
  enable: true
server-url:
  rest: localhost:9300/illegal
  open: localhost:8302/springOpenApi

openUrl: http://localhost:8302/springOpenApi/

